version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-task-management
    ports:
      - "27018:27017"
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
